POST http://localhost:3020/messages HTTP/1.1
Content-Type: text/turtle
Accept: text/turtle

@prefix  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix    r: <http://ontology.cf.ericsson.net/reasoner/> .
@prefix   rr: <http://ontology.cf.ericsson.net/reasoner/meta/> .
@prefix  ns1: <http://eriba/graph/> .

<message>
  a r:Message ;
  r:to r:KnowledgeBase ;
  r:graph "mygraph" ;
  r:subject "assert" .

ns1:Alice
  rdf:type ns1:Person ;
  ns1:age 30 .

###
POST http://localhost:3020/messages HTTP/1.1
Content-Type: text/turtle
Accept: text/turtle

@prefix  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix    r: <http://ontology.cf.ericsson.net/reasoner/> .
@prefix   rr: <http://ontology.cf.ericsson.net/reasoner/meta/> .
@prefix  ns1: <http://eriba/graph/> .

<message>
  a r:Message ;
  r:to r:KnowledgeBase ;
  r:graph "mygraph" ;
  r:subject "update" .

ns1:Alice
  ns1:age 31 .

###
POST http://localhost:3020/messages HTTP/1.1
Content-Type: text/turtle
Accept: text/turtle

@prefix  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix    r: <http://ontology.cf.ericsson.net/reasoner/> .
@prefix   rr: <http://ontology.cf.ericsson.net/reasoner/meta/> .
@prefix  ns1: <http://eriba/graph/> .

<message>
  a r:Message ;
  r:to r:KnowledgeBase ;
  r:graph "mygraph" ;
  r:subject "retract" .

ns1:Alice
  rdf:type ns1:Person ;
  ns1:age 31 .

###
POST http://localhost:3020/messages HTTP/1.1
Content-Type: text/turtle
Accept: text/turtle

@prefix  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix    r: <http://ontology.cf.ericsson.net/reasoner/> .
@prefix  ns1: <http://eriba/graph/> .

<message>
  a r:Message ;
  r:to r:KnowledgeBase ;
  r:subject "query" ;
  r:payload <patch> .

<patch>
  a r:Rule ;
  r:graph "mygraph" ;
  r:retract [ r:id ns1:Alice ;
              ns1:age 30
            ] ;
  r:assert [ r:id ns1:Alice ;
             ns1:age 31
           ] .

###
POST http://localhost:3020/messages HTTP/1.1
Content-Type: text/turtle
Accept: text/turtle

@prefix  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix    r: <http://ontology.cf.ericsson.net/reasoner/> .
@prefix    v: <http://ontology.cf.ericsson.net/reasoner/variables/> .
@prefix  ns1: <http://eriba/graph/> .

<message>
  a r:Message ;
  r:to r:KnowledgeBase ;
  r:subject "query" ;
  r:payload <patch> .

<patch>
  a r:Rule ;
  r:graph "mygraph" ;
  r:retract [ r:id ns1:Alice ;
              ns1:age v:_
            ] ;
  r:assert [ r:id ns1:Alice ;
             ns1:age 31
           ] .