[tool.poetry]
name = "openapi-to-rdf"
version = "0.1.0"
description = "Convert OpenAPI YAML specifications to RDF vocabularies and SHACL validation shapes for telecom intent-based automation and TMForum standards"
authors = ["Jean Martins <jean.martins@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/EricssonResearch/openapi-to-rdf"
repository = "https://github.com/EricssonResearch/openapi-to-rdf"
keywords = ["openapi", "rdf", "shacl", "TMF", "TMForum", "3gpp", "intents", "intent-based", "telecom", "telecommunications", "automation", "semantic-web", "network-management", "5g", "etsi"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Telecommunications Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: System :: Networking",
    "Topic :: Communications"
]
packages = [{include = "openapi_to_rdf"}]

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.2"
rdflib = "^7.1.3"
requests = "^2.32.5"

[tool.poetry.scripts]
openapi-to-rdf = "openapi_to_rdf.main:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
